require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://github.com/Cocoapods/Specs.git'

target 'RNSyrfClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Pods for RNSyrfClient
  pod 'SYRFLocation'
  
end
